export const DRIVE_FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const DRIVE_FETCHING_PROJECRS_FAILED = 'DRIVE_FETCHING_PROJECRS_FAILED';
export const DRIVE_FETCHING_PROJECRS_SUCCESS = 'DRIVE_FETCHING_PROJECRS_SUCCESS';

export const DRIVE_FETCHING_NOTES = 'DRIVE_FETCHING_NOTES';
export const DRIVE_FETCHING_NOTES_SUCCESS = 'DRIVE_FETCHING_NOTES_SUCCESS';
export const DRIVE_FETCHING_NOTES_FAILED = 'DRIVE_FETCHING_NOTES_FAILED';

export const DRIVE_BACK_ROOT = 'DRIVE_BACK_ROOT';

export const DRIVE_DOWNLOAD_NOTE = 'DRIVE_DOWNLOAD_NOTE';
export const DRIVE_DOWNLOAD_NOTE_SUCCESS = 'DRIVE_DOWNLOAD_NOTE_SUCCESS';
export const DRIVE_DOWNLOAD_NOTE_FAILED = 'DRIVE_DOWNLOAD_NOTE_FAILED';

export const DRIVE_DELETE_ITEM = 'DRIVE_DELETE_ITEM';
export const DRIVRE_DELETE_ITEM_SUCCESS = 'DRIVE_DELETE_ITEM_SUCCESS';
export const DRIVER_DELETE_ITEM_FAILED = 'DRIVE_DELETE_ITEM_FAILED';
