export const DRIVER_FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const DRIVER_FETCHING_PROJECRS_FAILED = 'DRIVER_FETCHING_PROJECRS_FAILED';
export const DRIVER_FETCHING_PROJECRS_SUCCESS = 'DRIVER_FETCHING_PROJECRS_SUCCESS';

export const DRIVER_FETCHING_NOTES = 'DRIVER_FETCHING_NOTES';
export const DRIVER_FETCHING_NOTES_SUCCESS = 'DRIVER_FETCHING_NOTES_SUCCESS';
export const DRIVER_FETCHING_NOTES_FAILED = 'DRIVER_FETCHING_NOTES_FAILED';

export const DRIVER_BACK_ROOT = 'DRIVER_BACK_ROOT';

export const DRIVER_DOWNLOAD_NOTE = 'DRIVER_DOWNLOAD_NOTE';
export const DRIVER_DOWNLOAD_NOTE_SUCCESS = 'DRIVER_DOWNLOAD_NOTE_SUCCESS';
export const DRIVER_DOWNLOAD_NOTE_FAILED = 'DRIVER_DOWNLOAD_NOTE_FAILED';
