/**
 * 文件导出队列
 */

export const EXPORT_INIT_QUEUE = 'EXPORT_INIT_QUEUE';
export const EXPORT_SUCCESS_SINGLE = 'EXPORT_SUCCESS_SINGLE';
export const EXPORT_FAILED_SINGLE = 'EXPORT_FAILED_SINGLE';
export const EXPORT_COMPOLETE = 'EXPORT_COMPOLETE';
