export const UPLOAD_IMAGE = 'UPLOAD_IMGAE';
export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const IMAGES_GET_LIST = 'IMAGES_GET_LIST';
