export const CHANGE_MEDIUM_AUTH = 'CHANGE_MEDIUM_AUTH';
export const AUTH_MEDIUM = 'AUTH_MEDIUM';
export const AUTH_MEDIUM_SUCCESS = 'AUTH_MEDIUM_SUCCESS';
export const AUTH_MEDIUM_FAILED = 'AUTH_MEDIUM_FAILED';
export const POST_MEDIUM = 'POST_MEDIUM';
export const POST_MEDIUM_SUCCESS = 'POST_MEDIUM_SUCCESS';
export const POST_MEDIUM_FAILED = 'POST_MEDIUM_FAILED';
