export const GET_USER_AVATAR = 'GET_USER_AVATAR';
export const GET_USER_AVATAR_SUCCESS = 'GET_USER_AVATAR_SUCCESS';
export const GET_USER_AVATAR_FAILED = 'GET_USER_AVATAR_FAILED';

export const SET_USER_LOCAL_AVATAR = 'SET_USER_LOCAL_AVATAR';
